Develop
aBoyarov/java-explore-with-me pull request #2
Opened 2022-10-07 19:17 UTC by aBoyarov

2022-10-08 04:18 UTC, eugene-lenkevich requested changes
Привет, Андрей, спасибо за PR

Первым делом поздравляю тебя с тем, что ты дошел до дипломной работы, ты крут без вариантов :) 

Далее, наша цель в том, чтобы сделать красоту в этом проекте, сама работа в целом сделана на отлично, но мы ее еще немного шлифанем. Оставил кучку коментариев.
 
Будут вопросы, задавай в слаке, немножко допилить осталось :)

Удачи!

2022-10-08 04:18 UTC, eugene-lenkevich commented on server/src/main/java/explorewithmeserver/repository/CategoryRepository.java
> +@Repository
@Repository вроде как можно и не писать и так работать будет, ниже, смотрю, на репозиториях ее и нет :)

2022-10-08 04:18 UTC, eugene-lenkevich commented on server/src/main/java/explorewithmeserver/model/event/Event.java
> +    @ManyToOne(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
Для @ManyToOne fetch = FetchType.EAGER по умолчанию, можно не указывать :) 

А вот для связи наоборот, @OneToMany, там где связывается коллекция объектов, наоборот, LAZY, что логично, иначе будут каждый раз выгружаться все связанные данные, при особо "грамотной" настройке можно умудрится всю базу вытащить одним запросом :)

2022-10-08 04:18 UTC, eugene-lenkevich commented on server/src/main/java/explorewithmeserver/service/registered/impl/UserEventServiceImpl.java
> +    private Event toEventFromUpdateDto(EventUpdateDto eventUpdateDto) {
Этот метод вроде как нигде не спользуется или мне кажется :)

2022-10-08 04:18 UTC, eugene-lenkevich commented on server/src/main/java/explorewithmeserver/service/all/impl/EventServiceImpl.java
> +        Pageable page = null;
Тут можно и просто написать Pageable page; а оноциализировтать потом :)

2022-10-08 04:18 UTC, eugene-lenkevich commented on server/src/main/resources/schema.sql
> +    description VARCHAR NOT NULL,
NOT NULL - я могу конечно ошибаться, но неужели описание обязательно? :)

2022-10-08 04:18 UTC, eugene-lenkevich commented on server/src/main/resources/schema.sql
> +    state VARCHAR,
Для статуса все таки лучше ограничить длину колонки, у нас же известные значения в эту колонку ложаться :)
Место на диске, конечно, дешевое, но все таки лучше пусть будут ограничения

2022-10-09 04:03 UTC, eugene-lenkevich approved these changes
Привет, спасибо за доработки, теперь все гут, спасибо :)

2022-10-15 13:45 UTC, RuslanDergachev commented on server/src/main/java/explorewithmeserver/service/registered/impl/UserEventServiceImpl.java
> +    public CommentDto addComment(Long userId, Long eventId, NewCommentDto newCommentDto) {
Андрей, метод реализован хорошо, но я бы добавил валидацию входящих аргументов

2022-10-15 13:46 UTC, aBoyarov commented on server/src/main/java/explorewithmeserver/service/registered/impl/UserEventServiceImpl.java
> +    public CommentDto addComment(Long userId, Long eventId, NewCommentDto newCommentDto) {
Ща сделаю

2022-10-15 13:51 UTC, aBoyarov commented on server/src/main/java/explorewithmeserver/service/registered/impl/UserEventServiceImpl.java
> +    public CommentDto addComment(Long userId, Long eventId, NewCommentDto newCommentDto) {
Готово

2022-10-15 13:59 UTC, RuslanDergachev commented on server/src/main/java/explorewithmeserver/service/registered/impl/UserEventServiceImpl.java
> +    public CommentDto addComment(Long userId, Long eventId, NewCommentDto newCommentDto) {
Отличная работа!

2022-10-16 12:28 UTC, merged